// request
export const REQUEST_PENDING = 'REQUEST_PENDING'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILED = 'REQUEST_FAILED'

// search
export const SEARCH = 'SEARCH'

export const REQUEST_URL_PENDING = 'REQUEST_URL_PENDING'
export const REQUEST_URL_SUCCESS = 'REQUEST_URL_SUCCESS'
export const REQUEST_URL_FAILED = 'REQUEST_URL_FAILED'

// request each data from server
export const REQUEST_EACH_DATA_PENDING = 'REQUEST_PENDING'
export const REQUEST_EACH_DATA_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_EACH_DATA_FAILED = 'REQUEST_FAILED'
/*
export const actions = {
    REQUEST_PEOPLE_PENDING : 'REQUEST_PEOPLE_PENDING',
    REQUEST_PEOPLE_SUCCESS : 'REQUEST_PEOPLE_SUCCESS',
    REQUEST_PEOPLE_FAILED : 'REQUEST_PEOPLE_FAILED',

    REQUEST_VEHICLES_PENDING : 'REQUEST_VEHICLES_PENDING',
    REQUEST_VEHICLES_SUCCESS : 'REQUEST_VEHICLES_SUCCESS',
    REQUEST_VEHICLES_FAILED : 'REQUEST_VEHICLES_FAILED',

    REQUEST_PLANETS_PENDING : 'REQUEST_PLANETS_PENDING',
    REQUEST_PLANETS_SUCCESS : 'REQUEST_PLANETS_SUCCESS',
    REQUEST_PLANETS_FAILED : 'REQUEST_PLANETS_FAILED',

    REQUEST_SPACESHIPS_PENDING : 'REQUEST_SPACESHIPS_PENDING',
    REQUEST_SPACESHIPS_SUCCESS : 'REQUEST_SPACESHIPS_SUCCESS',
    REQUEST_SPACESHIPS_FAILED : 'REQUEST_SPACESHIPS_FAILED',

    REQUEST_SPECIES_PENDING : 'REQUEST_SPECIES_PENDING',
    REQUEST_SPECIES_SUCCESS : 'REQUEST_SPECIES_SUCCESS',
    REQUEST_SPECIES_FAILED : 'REQUEST_SPECIES_FAILED',

    REQUEST_FILMS_PENDING : 'REQUEST_FILMS_PENDING',
    REQUEST_FILMS_SUCCESS : 'REQUEST_FILMS_SUCCESS',
    REQUEST_FILMS_FAILED : 'REQUEST_FILMS_FAILED'
}

*/
