// request
export const REQUEST_PENDING = 'REQUEST_PENDING'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILED = 'REQUEST_FAILED'

// search
export const SEARCH = 'SEARCH'

export const REQUEST_URL_PENDING = 'REQUEST_URL_PENDING'
export const REQUEST_URL_SUCCESS = 'REQUEST_URL_SUCCESS'
export const REQUEST_URL_FAILED = 'REQUEST_URL_FAILED'

// request each data from server
export const REQUEST_EACH_DATA_PENDING = 'REQUEST_PENDING'
export const REQUEST_EACH_DATA_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_EACH_DATA_FAILED = 'REQUEST_FAILED'
